version: '3'

services:
  whoami:
    image: containous/whoami
    networks:
      - frontproxynet
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.scheme=http"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.rule=Host(${HOSTNAME})"
      - "traefik.http.routers.whoami.service=whoami"

networks:
  frontproxynet:
    external: true
