
version: '3'

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - frontproxynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=8089"
      - "traefik.backend=traefik"
      - "traefik.frontend=traefik"

networks:
  frontproxynet:
    external: true