[log]
  level = "WARNING"

# Limiting the Logs to Specific Fields
[accessLog]
  filePath = "/access.log"

  [accessLog.filters]
    statusCodes = ["400-403", "300-302", "500-503"]
    minDuration = "700ms"

[global]
  checkNewVersion = false
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

[api]
  debug = false
  insecure = false
  dashboard = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false
  network = "frontproxynet"

[certificatesResolvers.sample.acme]
  email = "xxxx@xxxx.com"
  storage = "acme.json"
  [certificatesResolvers.sample.acme.httpChallenge]
    entryPoint = "http"
