debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
  [entryPoints.dashboard]
  address = ":8089"

[api]
entryPoint = "dashboard"
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
network = "frontproxynet"
domain = "docker.test"

[acme]
email = "xxxx@xxxx.com"
storage = "acme.json"
onDemand = false
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"