[log]
  level = "ERROR"

[global]
  checkNewVersion = false
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.http]
    address = ":80"

  [entryPoints.https]
    address = ":443"

[api]
  insecure = false
  dashboard = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false
  network = "frontproxynet"

[certificatesResolvers.sample.acme]
  email = "xxxx@xxxx.com"
  storage = "acme.json"
  [certificatesResolvers.sample.acme.httpChallenge]
    entryPoint = "http"
