version: "3"
services:
  nginx:
    restart: always
    image: jwilder/nginx-proxy
    environment:
        ENABLE_IPV6: "true"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./../../front-proxy/htpasswd:/etc/nginx/htpasswd:ro
      - ./../../front-proxy/certs:/etc/nginx/certs:ro
      - ./../../front-proxy/vhost.d:/etc/nginx/vhost.d
      - ./../../front-proxy/html:/usr/share/nginx/html
      - ./../../front-proxy/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./../../front-proxy/certs:/etc/nginx/certs:rw
      - ./../../front-proxy/htpasswd:/etc/nginx/htpasswd:ro
      - ./../../front-proxy/vhost.d:/etc/nginx/vhost.d
      - ./../../front-proxy/html:/usr/share/nginx/html
      - ./../../front-proxy/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro
networks:
  default:
    external:
      name: frontproxynet
