version: '3'
services:
  MAIN:
    hostname: example
    image: roadiz/standard-edition
    networks: 
      - default
      - frontproxynet
    environment:
      VIRTUAL_HOST: example.localhost,www.example.localhost
      #LETSENCRYPT_HOST: example.localhost,www.example.localhost
      #LETSENCRYPT_EMAIL: contact@example.localhost
    volumes:
      - DATA:/data
    links:
      - DB:mariadb
      #- SOLR:solr
    depends_on:
      - DB
      #- SOLR
    restart: always
    # If using Traefik 
    # https://docs.traefik.io/user-guide/docker-and-lets-encrypt/
    #labels:
    #  - "traefik.docker.network=example"
    #  - "traefik.enable=true"
    #  - "traefik.basic.frontend.rule=Host:app.my-awesome-app.org"
    #  - "traefik.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5m0s
      timeout: 5s
      retries: 3
  DB:
    hostname: example-db
    image: ambroisemaupate/mariadb
    networks: 
      - default
    environment:
      MARIADB_USER: "username"
      MARIADB_DB:   "username"
      MARIADB_PASS: "password"
    restart: always
    volumes:
      - DBDATA:/data
  # SSH container linked to db to
  # export or import mysqldumps and
  # sync your files from/to your local server
  SSH:
    hostname: example-ssh
    image: ambroisemaupate/light-ssh
    restart: "no"
    networks: 
      - default
    environment:
      PASS: "password"
    volumes:
      - DATA:/data
    links:
      - DB:mariadb
    depends_on:
      - DB
    ports:
      - "22/tcp"
  #SOLR:
  #  hostname: example-solr
  #  image: solr
  #  restart: always
  #  networks: 
  #    - default
  #  #ports:
  #  # - "8983:8983"
  #  #volumes:
  #  #  - SOLRDATA:/opt/solr/server/solr/mycores
  #  entrypoint:
  #    - docker-entrypoint.sh
  #    - solr-precreate
  #    - example
volumes:
  DATA:
  DBDATA:
  #SOLRDATA:

networks:
  frontproxynet:
    external: true